language: python
dist: bionic

cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

addons:
  apt:
    packages:
      - sqlite3
      - fping
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - spatialite-bin
      - libsqlite3-mod-spatialite

services:
  - docker
  - redis-server

branches:
  only:
    - master

before_install:
  - docker run -d --name influxdb -p 8086:8086 influxdb
  - docker exec -it influxdb influx -execute 'CREATE DATABASE openwisp2'
  - pip install -U pip wheel setuptools
  - pip install $DJANGO
  - pip install -U -r requirements-test.txt

install:
  - pip install -e .
  # temporary: remove when openwisp-utils 0.5.0 is released
  - pip install -U https://github.com/openwisp/openwisp-utils/tarball/master#egg=openwisp_utils[qa]

script:
  - ./run-qa-checks
  - coverage run --source=openwisp_monitoring runtests.py

after_success:
  coveralls
