language: python
dist: bionic
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django~=2.2"
  - DJANGO="django~=3.0"
  - DJANGO="django~=3.1"

addons:
  apt:
    packages:
      - sqlite3
      - fping
      - gdal-bin
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - spatialite-bin
      - libsqlite3-mod-spatialite

services:
  - docker
  - redis-server

branches:
  only:
    - master
    - dev

before_install:
  - docker run -d --name influxdb -e INFLUXDB_DB=openwisp2 -p 8086:8086 influxdb:alpine
  - pip install -U "pip==20.2.4" wheel setuptools
  - pip install -U -r requirements-test.txt
  - pip install -U $DJANGO

install:
  - pip install -e .
  - sh install-dev.sh

script:
  - ./run-qa-checks
  - SAMPLE_APP=1 coverage run --source=openwisp_monitoring runtests.py
  - coverage run -a --source=openwisp_monitoring runtests.py

jobs:
  include:
    - stage: Deploy
      before_install: skip
      install: skip
      if: type = push AND branch = master
      script:
        - echo "$DOCKER_TOKEN" | docker login --username $DOCKER_USERNAME --password-stdin
        - docker build . -t openwisp/openwisp-monitoring:develop
        - docker push openwisp/openwisp-monitoring:develop

after_success:
  coveralls


notifications:
  # will post a summary as a comment on github in case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never
